const { greet, readFile, readFileSync, readImg, writeFile, writeImg, getFileInfo, readStream, writeStream, pipes } = require('./hello')
// greet('morning')
// readFile()
// readImg()
// readFileSync()
// writeFile()
// writeImg()
// getFileInfo()
// readStream()
// writeStream()
pipes()